name: Build Masscan for ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64] # 目标架构
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 QEMU（用于交叉编译）
        uses: docker/setup-qemu-action@v3

      - name: 安装 ARM64 交叉编译工具链
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make

      - name: 编译 Masscan（ARM64，使用多线程）
        run: |
          make -j4 CROSS_COMPILE=aarch64-linux-gnu-

      - name: 安装 Masscan（可选）
        run: |
          sudo make install

      - name: 查看编译后的二进制文件
        run: |
          file bin/masscan

      - name: 上传构建的 ARM64 二进制文件
        uses: actions/upload-artifact@v4
        with:
          name: masscan-arm64
          path: bin/masscan
